// flow-typed signature: 8f280d581b3762f6e40697c6655c6f15
// flow-typed version: <<STUB>>/@blueprintjs/datetime_v^1.4.0/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@blueprintjs/datetime'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module '@blueprintjs/datetime' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@blueprintjs/datetime/dist/common/classes' {
  declare module.exports: any;
}

declare module '@blueprintjs/datetime/dist/common/dateUtils' {
  declare module.exports: any;
}

declare module '@blueprintjs/datetime/dist/common/errors' {
  declare module.exports: any;
}

declare module '@blueprintjs/datetime/dist/common/utils' {
  declare module.exports: any;
}

declare module '@blueprintjs/datetime/dist/dateInput' {
  declare module.exports: any;
}

declare module '@blueprintjs/datetime/dist/datePicker' {
  declare module.exports: any;
}

declare module '@blueprintjs/datetime/dist/datePickerCaption' {
  declare module.exports: any;
}

declare module '@blueprintjs/datetime/dist/datePickerCore' {
  declare module.exports: any;
}

declare module '@blueprintjs/datetime/dist/dateRangePicker' {
  declare module.exports: any;
}

declare module '@blueprintjs/datetime/dist/dateTimePicker' {
  declare module.exports: any;
}

declare module '@blueprintjs/datetime/dist/index' {
  declare module.exports: any;
}

declare module '@blueprintjs/datetime/dist/timePicker' {
  declare module.exports: any;
}

// Filename aliases
declare module '@blueprintjs/datetime/dist/common/classes.js' {
  declare module.exports: $Exports<'@blueprintjs/datetime/dist/common/classes'>;
}
declare module '@blueprintjs/datetime/dist/common/dateUtils.js' {
  declare module.exports: $Exports<'@blueprintjs/datetime/dist/common/dateUtils'>;
}
declare module '@blueprintjs/datetime/dist/common/errors.js' {
  declare module.exports: $Exports<'@blueprintjs/datetime/dist/common/errors'>;
}
declare module '@blueprintjs/datetime/dist/common/utils.js' {
  declare module.exports: $Exports<'@blueprintjs/datetime/dist/common/utils'>;
}
declare module '@blueprintjs/datetime/dist/dateInput.js' {
  declare module.exports: $Exports<'@blueprintjs/datetime/dist/dateInput'>;
}
declare module '@blueprintjs/datetime/dist/datePicker.js' {
  declare module.exports: $Exports<'@blueprintjs/datetime/dist/datePicker'>;
}
declare module '@blueprintjs/datetime/dist/datePickerCaption.js' {
  declare module.exports: $Exports<'@blueprintjs/datetime/dist/datePickerCaption'>;
}
declare module '@blueprintjs/datetime/dist/datePickerCore.js' {
  declare module.exports: $Exports<'@blueprintjs/datetime/dist/datePickerCore'>;
}
declare module '@blueprintjs/datetime/dist/dateRangePicker.js' {
  declare module.exports: $Exports<'@blueprintjs/datetime/dist/dateRangePicker'>;
}
declare module '@blueprintjs/datetime/dist/dateTimePicker.js' {
  declare module.exports: $Exports<'@blueprintjs/datetime/dist/dateTimePicker'>;
}
declare module '@blueprintjs/datetime/dist/index.js' {
  declare module.exports: $Exports<'@blueprintjs/datetime/dist/index'>;
}
declare module '@blueprintjs/datetime/dist/timePicker.js' {
  declare module.exports: $Exports<'@blueprintjs/datetime/dist/timePicker'>;
}
