// flow-typed signature: 246cac476ffec1f157eca5e256c89258
// flow-typed version: <<STUB>>/material-ui-datatables_v^0.16.4/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui-datatables'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui-datatables' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui-datatables/DataTables/DataTables' {
  declare module.exports: any;
}

declare module 'material-ui-datatables/DataTables/DataTablesHeaderColumn' {
  declare module.exports: any;
}

declare module 'material-ui-datatables/DataTables/DataTablesHeaderToolbar' {
  declare module.exports: any;
}

declare module 'material-ui-datatables/DataTables/DataTablesRow' {
  declare module.exports: any;
}

declare module 'material-ui-datatables/DataTables/DataTablesRowColumn' {
  declare module.exports: any;
}

declare module 'material-ui-datatables/DataTables/DataTablesTable' {
  declare module.exports: any;
}

declare module 'material-ui-datatables/DataTables/DataTablesTableBody' {
  declare module.exports: any;
}

declare module 'material-ui-datatables/DataTables/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui-datatables/DataTables/DataTables.js' {
  declare module.exports: $Exports<'material-ui-datatables/DataTables/DataTables'>;
}
declare module 'material-ui-datatables/DataTables/DataTablesHeaderColumn.js' {
  declare module.exports: $Exports<'material-ui-datatables/DataTables/DataTablesHeaderColumn'>;
}
declare module 'material-ui-datatables/DataTables/DataTablesHeaderToolbar.js' {
  declare module.exports: $Exports<'material-ui-datatables/DataTables/DataTablesHeaderToolbar'>;
}
declare module 'material-ui-datatables/DataTables/DataTablesRow.js' {
  declare module.exports: $Exports<'material-ui-datatables/DataTables/DataTablesRow'>;
}
declare module 'material-ui-datatables/DataTables/DataTablesRowColumn.js' {
  declare module.exports: $Exports<'material-ui-datatables/DataTables/DataTablesRowColumn'>;
}
declare module 'material-ui-datatables/DataTables/DataTablesTable.js' {
  declare module.exports: $Exports<'material-ui-datatables/DataTables/DataTablesTable'>;
}
declare module 'material-ui-datatables/DataTables/DataTablesTableBody.js' {
  declare module.exports: $Exports<'material-ui-datatables/DataTables/DataTablesTableBody'>;
}
declare module 'material-ui-datatables/DataTables/index.js' {
  declare module.exports: $Exports<'material-ui-datatables/DataTables/index'>;
}
declare module 'material-ui-datatables/index' {
  declare module.exports: $Exports<'material-ui-datatables'>;
}
declare module 'material-ui-datatables/index.js' {
  declare module.exports: $Exports<'material-ui-datatables'>;
}
