// flow-typed signature: 73b7fb7e2081291e1f96230bb0704959
// flow-typed version: <<STUB>>/react-data-grid_v^1.0.81/flow_v0.37.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-data-grid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-data-grid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-data-grid/addons' {
  declare module.exports: any;
}

declare module 'react-data-grid/dist/react-data-grid' {
  declare module.exports: any;
}

declare module 'react-data-grid/dist/react-data-grid.min' {
  declare module.exports: any;
}

declare module 'react-data-grid/dist/react-data-grid.ui-plugins' {
  declare module.exports: any;
}

declare module 'react-data-grid/dist/react-data-grid.ui-plugins.min' {
  declare module.exports: any;
}

declare module 'react-data-grid/docs/utils/generalUtils' {
  declare module.exports: any;
}

declare module 'react-data-grid/docs/utils/generateMarkdown' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-data-grid/addons.js' {
  declare module.exports: $Exports<'react-data-grid/addons'>;
}
declare module 'react-data-grid/dist/react-data-grid.js' {
  declare module.exports: $Exports<'react-data-grid/dist/react-data-grid'>;
}
declare module 'react-data-grid/dist/react-data-grid.min.js' {
  declare module.exports: $Exports<'react-data-grid/dist/react-data-grid.min'>;
}
declare module 'react-data-grid/dist/react-data-grid.ui-plugins.js' {
  declare module.exports: $Exports<'react-data-grid/dist/react-data-grid.ui-plugins'>;
}
declare module 'react-data-grid/dist/react-data-grid.ui-plugins.min.js' {
  declare module.exports: $Exports<'react-data-grid/dist/react-data-grid.ui-plugins.min'>;
}
declare module 'react-data-grid/docs/utils/generalUtils.js' {
  declare module.exports: $Exports<'react-data-grid/docs/utils/generalUtils'>;
}
declare module 'react-data-grid/docs/utils/generateMarkdown.js' {
  declare module.exports: $Exports<'react-data-grid/docs/utils/generateMarkdown'>;
}
declare module 'react-data-grid/index' {
  declare module.exports: $Exports<'react-data-grid'>;
}
declare module 'react-data-grid/index.js' {
  declare module.exports: $Exports<'react-data-grid'>;
}
