export const ADD_TOASTS = 'ADD_TOASTS';
export const CLEAR_TOASTS = 'CLEAR_TOASTS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CONTADOR = 'SET_CONTADOR';
export const ISEMPTY_CONTADOR = 'ISEMPTY_CONTADOR';
export const AUMT_CONTADOR = 'AUMT_CONTADOR';
